/** ISO-style country names for onboarding (static list). */
export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Argentina', 'Australia', 'Austria', 'Bangladesh',
  'Belgium', 'Brazil', 'Canada', 'Chile', 'China', 'Colombia', 'Czech Republic', 'Denmark',
  'Egypt', 'Ethiopia', 'Finland', 'France', 'Germany', 'Ghana', 'Greece', 'Hong Kong',
  'Hungary', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Japan',
  'Jordan', 'Kenya', 'Malaysia', 'Mexico', 'Morocco', 'Netherlands', 'New Zealand',
  'Nigeria', 'Norway', 'Pakistan', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Romania',
  'Russia', 'Saudi Arabia', 'Sierra Leone', 'Singapore', 'South Africa', 'South Korea', 'Spain',
  'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine', 'United Arab Emirates',
  'United Kingdom', 'United States', 'Vietnam', 'Other',
].sort((a, b) => a.localeCompare(b));

const COUNTRY_CONTINENT = {
  Afghanistan: 'Asia',
  Albania: 'Europe',
  Algeria: 'Africa',
  Argentina: 'South America',
  Australia: 'Oceania',
  Austria: 'Europe',
  Bangladesh: 'Asia',
  Belgium: 'Europe',
  Brazil: 'South America',
  Canada: 'North America',
  Chile: 'South America',
  China: 'Asia',
  Colombia: 'South America',
  'Czech Republic': 'Europe',
  Denmark: 'Europe',
  Egypt: 'Africa',
  Ethiopia: 'Africa',
  Finland: 'Europe',
  France: 'Europe',
  Germany: 'Europe',
  Ghana: 'Africa',
  Greece: 'Europe',
  'Hong Kong': 'Asia',
  Hungary: 'Europe',
  India: 'Asia',
  Indonesia: 'Asia',
  Iran: 'Asia',
  Iraq: 'Asia',
  Ireland: 'Europe',
  Israel: 'Asia',
  Italy: 'Europe',
  Japan: 'Asia',
  Jordan: 'Asia',
  Kenya: 'Africa',
  Malaysia: 'Asia',
  Mexico: 'North America',
  Morocco: 'Africa',
  Netherlands: 'Europe',
  'New Zealand': 'Oceania',
  Nigeria: 'Africa',
  Norway: 'Europe',
  Pakistan: 'Asia',
  Peru: 'South America',
  Philippines: 'Asia',
  Poland: 'Europe',
  Portugal: 'Europe',
  Romania: 'Europe',
  Russia: 'Europe',
  'Saudi Arabia': 'Asia',
  'Sierra Leone': 'Africa',
  Singapore: 'Asia',
  'South Africa': 'Africa',
  'South Korea': 'Asia',
  Spain: 'Europe',
  Sweden: 'Europe',
  Switzerland: 'Europe',
  Taiwan: 'Asia',
  Thailand: 'Asia',
  Turkey: 'Asia',
  Ukraine: 'Europe',
  'United Arab Emirates': 'Asia',
  'United Kingdom': 'Europe',
  'United States': 'North America',
  Vietnam: 'Asia',
};

/** @param {string} country @param {string} [customCountry] */
export function getContinentForCountry(country, customCountry) {
  if (country === 'Other') {
    if (!customCountry?.trim()) return null;
    return getContinentForCountry(customCountry.trim());
  }
  return COUNTRY_CONTINENT[country] ?? null;
}
