// Keep route import functions stable so navigation can preload the same module
// React.lazy() will consume. This avoids downloading every page at startup.
export const routeModules = {
  dashboard: () => import("@/pages/Dashboard"),
  library: () => import("@/pages/Library"),
  bookDetail: () => import("@/pages/BookDetail"),
  studySession: () => import("@/pages/StudySession"),
  flashcardSets: () => import("@/pages/FlashcardSets"),
  quizHistory: () => import("@/pages/QuizHistory"),
  quizResultDetail: () => import("@/pages/QuizResultDetail"),
  analytics: () => import("@/pages/Analytics"),
  billingUsage: () => import("@/pages/BillingUsage"),
  settings: () => import("@/pages/Settings"),
  userManagement: () => import("@/pages/UserManagement"),
  profile: () => import("@/pages/Profile"),
  quizChallenges: () => import("@/pages/QuizChallenges"),
  folders: () => import("@/pages/Folders"),
  leaderboard: () => import("@/pages/Leaderboard"),
  challengeLeaderboard: () => import("@/pages/ChallengeLeaderboard"),
  studyGroups: () => import("@/pages/StudyGroups"),
  studyGroupDetail: () => import("@/pages/StudyGroupDetail"),
  sharedStudySession: () => import("@/pages/SharedStudySession"),
  dailyReview: () => import("@/pages/DailyReview"),
  achievements: () => import("@/pages/Achievements"),
  scorecards: () => import("@/pages/Scorecards"),
  feedback: () => import("@/pages/Feedback"),
  guide: () => import("@/pages/UserGuide"),
  pricing: () => import("@/pages/Pricing"),
  onboarding: () => import("@/pages/Onboarding"),
  login: () => import("@/pages/Login"),
  emailVerification: () => import("@/pages/EmailVerification"),
  billingSuccess: () => import("@/pages/BillingSuccess"),
  creditBillingSuccess: () => import("@/pages/CreditBillingSuccess"),
  billingCancel: () => import("@/pages/BillingCancel"),
  mobileBillingSuccess: () => import("@/pages/MobileBillingSuccess"),
  mobileBillingCancel: () => import("@/pages/MobileBillingCancel"),
  mobileCreditBillingSuccess: () => import("@/pages/MobileCreditBillingSuccess"),
  mobileCreditBillingCancel: () => import("@/pages/MobileCreditBillingCancel"),
};

export const routePreloads = {
  "/": routeModules.dashboard,
  "/library": routeModules.library,
  "/flashcard-sets": routeModules.flashcardSets,
  "/quiz-history": routeModules.quizHistory,
  "/challenges": routeModules.quizChallenges,
  "/challenge-leaderboard": routeModules.challengeLeaderboard,
  "/daily-review": routeModules.dailyReview,
  "/analytics": routeModules.analytics,
  "/scorecards": routeModules.scorecards,
  "/leaderboard": routeModules.leaderboard,
  "/study-groups": routeModules.studyGroups,
  "/guide": routeModules.guide,
  "/pricing": routeModules.pricing,
  "/billing": routeModules.billingUsage,
  "/users": routeModules.userManagement,
};
