import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import client from '../api/client';
import DataTable from '../components/DataTable';
import MetricCard from '../components/MetricCard';
import { DetailRows, EmptyState, PageHeader, QueryState, SectionCard, StatusBadge } from '../components/AdminUI';

const get = async (url, params) => (await client.get(url, { params })).data;
const when = (v) => v ? new Date(v).toLocaleString() : '—';
const json = (v) => <pre className="safe-json">{JSON.stringify(v, null, 2)}</pre>;
function Loading({ query }) {
  return <QueryState query={query} />;
}

export function Overview() {
  const activity = useQuery({ queryKey:['control-activity'], queryFn:()=>get('/admin/control/activity-analytics') });
  const onboarding = useQuery({ queryKey:['control-onboarding'], queryFn:()=>get('/admin/control/onboarding-analytics') });
  const subs = useQuery({ queryKey:['control-sub-summary'], queryFn:()=>get('/admin/control/subscriptions',{size:1}) });
  const plans = useQuery({ queryKey:['control-plans'], queryFn:()=>get('/admin/control/plan-rankings') });
  if ([activity,onboarding,subs,plans].some(x=>x.isLoading)) return <p>Loading operational overview…</p>;
  const rank = x => x?.map(v=>v.plan).join(' + ') || 'Not available';
  return <div><PageHeader title="Overview" description="What is happening across MindFlip right now." />
    <div className="metrics-grid"><MetricCard label="Total users" value={subs.data?.summary?.total_users}/><MetricCard label="Active users (30d)" value={activity.data?.mau}/><MetricCard label="Paying users" value={subs.data?.summary?.paying_users}/><MetricCard label="New this week" value={onboarding.data?.last_7_days.registrations}/></div>
    <SectionCard title="Growth and activity" description="Meaningful authenticated activity in UTC rolling windows."><div className="metrics-grid"><MetricCard label="New today" value={onboarding.data?.today.registrations}/><MetricCard label="Onboarded today" value={onboarding.data?.today.completed}/><MetricCard label="DAU" value={activity.data?.dau}/><MetricCard label="WAU" value={activity.data?.wau}/></div></SectionCard>
    <SectionCard title="Subscriptions" description="Canonical synchronized billing state."><div className="metrics-grid">{['free_users','paying_users','trialing','canceling','past_due','conflicts'].map(k=><MetricCard key={k} label={k.replaceAll('_',' ')} value={subs.data?.summary?.[k] ?? 0}/>)}</div></SectionCard>
    <SectionCard title="Plan ranking" description={plans.data?.all_tied ? 'Configured plan buckets are tied.' : 'Customer distribution by resolved entitlement.'}><div className="metrics-grid"><MetricCard label={plans.data?.all_tied?'Tied plans':'Most popular'} value={rank(plans.data?.highest)}/>{!plans.data?.all_tied&&<><MetricCard label="Second" value={rank(plans.data?.second_highest)}/><MetricCard label="Least popular" value={rank(plans.data?.lowest)}/></>}</div></SectionCard>
  </div>;
}

export function Subscriptions() {
  const [page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState(''),[plan,setPlan]=useState(''),[special,setSpecial]=useState(''),[expiring,setExpiring]=useState('');
  const params={page,size:25,q,status:status||undefined,plan:plan||undefined,expiring_days:expiring||undefined};
  if(special==='trial')params.trial=true;if(special==='canceling')params.canceling=true;if(special==='conflict')params.conflict=true;
  const query=useQuery({queryKey:['control-subs',page,q,status,plan,special,expiring],queryFn:()=>get('/admin/control/subscriptions',params)});
  const columns=[{key:'user',label:'User',render:r=><Link to={`/users/${r.user_id}`}>{r.user}</Link>},{key:'email',label:'Email'},{key:'plan',label:'Plan',render:r=><StatusBadge value={r.plan}/>},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>},{key:'period_end',label:'Renews / Ends',render:r=>when(r.period_end)},{key:'days',label:'Days remaining',render:r=>r.time.label},{key:'auto_renew',label:'Auto renew',render:r=>r.auto_renew?'Yes':'No'},{key:'conflict',label:'Conflict',render:r=>r.conflict?<StatusBadge value="Conflict"/>:'—'}];
  const change=setter=>e=>{setter(e.target.value);setPage(1)};
  return <div><h1>Subscriptions</h1><div className="filters-row"><input value={q} onChange={change(setQ)} placeholder="Search user or email…"/><input value={plan} onChange={change(setPlan)} placeholder="Exact plan name…"/><select value={status} onChange={change(setStatus)}><option value="">All statuses</option>{['active','trialing','past_due','canceled','free','billing_conflict'].map(x=><option key={x}>{x}</option>)}</select><select value={special} onChange={change(setSpecial)}><option value="">All states</option><option value="trial">Trials</option><option value="canceling">Canceling</option><option value="conflict">Billing conflicts</option></select><select value={expiring} onChange={change(setExpiring)}><option value="">Any end date</option><option value="7">Ending in 7 days</option><option value="30">Ending in 30 days</option></select></div><div className="metrics-grid">{Object.entries(query.data?.summary||{}).map(([k,v])=><MetricCard key={k} label={k.replaceAll('_',' ')} value={v}/>)}</div><Loading query={query}/>{query.data&&<DataTable columns={columns} rows={query.data.items.map(x=>({...x,id:x.user_id}))} page={page} total={query.data.total} size={25} onPageChange={setPage}/>}</div>;
}

export function UserDetail() {
 const {id}=useParams(); const q=useQuery({queryKey:['control-user',id],queryFn:()=>get(`/admin/control/users/${id}`)}); if(q.isLoading||q.isError)return <Loading query={q}/>; const d=q.data;
 const accountRows=[['Email',d.account.email],['Status',<StatusBadge value={d.account.status}/>],['Role',d.account.role],['Joined',when(d.account.created_at)],['Last active',when(d.account.last_active_at)],['Onboarding',d.account.onboarding_completed?'Complete':'Incomplete'],['Location',[d.account.country,d.account.continent].filter(Boolean).join(', ')||'—']];
 const subscriptionRows=[['Plan',d.subscription.plan],['Status',<StatusBadge value={d.subscription.status}/>],['Renews / ends',when(d.subscription.current_period_end)],['Time remaining',d.subscription.time?.label],['Auto renew',d.subscription.cancel_at_period_end?'No':'Yes'],['Last synchronized',when(d.subscription.last_sync_at)]];
 const activityRows=Object.entries(d.activity).map(([key,value])=>[key.replaceAll('_',' '),value]);
 return <div><Link to="/users">← Users</Link><PageHeader title={d.account.name} description={d.account.email}/><div className="detail-grid"><SectionCard title="Account"><DetailRows rows={accountRows}/></SectionCard><SectionCard title="Subscription" className={d.subscription.conflict?'danger-zone':''}><DetailRows rows={subscriptionRows}/></SectionCard><SectionCard title="Credit balances"><DetailRows rows={Object.entries(d.credits).filter(([,v])=>typeof v!=='object').map(([k,v])=>[k.replaceAll('_',' '),v])}/></SectionCard><SectionCard title="Activity and learning"><DetailRows rows={activityRows}/></SectionCard></div><SectionCard title="Invoices">{d.invoices.length?json(d.invoices):<EmptyState title="No invoices" description="This account has no synchronized invoices."/>}</SectionCard><SectionCard title="Credit purchases">{d.credit_purchases.length?json(d.credit_purchases):<EmptyState title="No credit purchases" description="This account has not purchased additional credits."/>}</SectionCard><SectionCard title="Recent credit ledger">{d.credit_ledger.length?json(d.credit_ledger):<EmptyState title="No credit activity" description="No ledger entries are available for this account."/>}</SectionCard></div>;
}

export function BillingOperations(){const qc=useQueryClient();const q=useQuery({queryKey:['billing-ops'],queryFn:()=>get('/admin/control/billing-operations')});const reconcile=useMutation({mutationFn:()=>client.post('/admin/billing/reconcile'),onSuccess:()=>qc.invalidateQueries({queryKey:['billing-ops']})});return <div><div className="section-title"><h1>Billing Operations</h1><button disabled={reconcile.isPending} onClick={()=>{if(window.confirm('Run explicit Stripe reconciliation now?'))reconcile.mutate()}}>{reconcile.isPending?'Reconciling…':'Reconcile Stripe'}</button></div><p className="text-muted">Uses synchronized billing facts. Reconciliation is explicit and audited; tables never fetch Stripe once per row.</p><Loading query={q}/>{q.data&&<><div className="metrics-grid">{Object.entries(q.data.summary).map(([k,v])=><MetricCard key={k} label={k.replaceAll('_',' ')} value={v}/>)}</div><h2>Failed / processing webhooks</h2>{json(q.data.events)}<h2>Recent invoices</h2>{json(q.data.invoices)}<h2>Credit purchases</h2>{json(q.data.credit_purchases)}</>}</div>}
export function AuditLog(){
 const [page,setPage]=useState(1),[qv,setQv]=useState(''),[action,setAction]=useState(''),[resource,setResource]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState('');
 const q=useQuery({queryKey:['audit',page,qv,action,resource,dateFrom,dateTo],queryFn:()=>get('/admin/control/audit-log',{page,size:50,q:qv,action:action||undefined,resource:resource||undefined,date_from:dateFrom||undefined,date_to:dateTo||undefined})});
 const cols=[{key:'created_at',label:'Time',render:r=>when(r.created_at)},{key:'admin_email',label:'Admin'},{key:'action',label:'Action'},{key:'resource_type',label:'Resource'},{key:'resource_id',label:'Target'},{key:'reason',label:'Reason'},{key:'metadata',label:'Safe changes',render:r=><details><summary>View</summary>{json({previous:r.previous,new:r.new,metadata:r.metadata,request_id:r.request_id})}</details>}];
 const change=setter=>e=>{setter(e.target.value);setPage(1)};
 return <div><h1>Admin Audit Log</h1><div className="filters-row"><input value={qv} onChange={change(setQv)} placeholder="Search admin or user ID…"/><input value={action} onChange={change(setAction)} placeholder="Action…"/><input value={resource} onChange={change(setResource)} placeholder="Resource type…"/><label>From <input type="date" value={dateFrom} onChange={change(setDateFrom)}/></label><label>To <input type="date" value={dateTo} onChange={change(setDateTo)}/></label></div><Loading query={q}/>{q.data&&<DataTable columns={cols} rows={q.data.items} page={page} total={q.data.total} size={50} onPageChange={setPage}/>}</div>
}
export function ActivityAnalytics(){const a=useQuery({queryKey:['activity'],queryFn:()=>get('/admin/control/activity-analytics')});const o=useQuery({queryKey:['onboarding'],queryFn:()=>get('/admin/control/onboarding-analytics')});return <div><h1>Growth & Activity</h1><Loading query={a}/><Loading query={o}/>{a.data&&<><p>{a.data.definition}</p><div className="metrics-grid">{['dau','wau','mau','returning_users_30d','inactive_users_30d'].map(k=><MetricCard key={k} label={k.replaceAll('_',' ')} value={a.data[k]}/>)}</div></>}{o.data&&<><h2>Onboarding (UTC)</h2><div className="metrics-grid">{['today','yesterday','last_7_days','last_30_days'].map(k=><MetricCard key={k} label={k.replaceAll('_',' ')} value={`${o.data[k].completed}/${o.data[k].registrations} (${o.data[k].completion_pct}%)`}/>)}</div>{json(o.data.daily)}</>}</div>}
export function LeaderboardMonitoring(){const q=useQuery({queryKey:['leaderboard-monitor'],queryFn:()=>get('/admin/control/leaderboards')});return <div><h1>Leaderboard Integrity</h1><Loading query={q}/>{q.data&&<><p>{q.data.anomaly_rule}</p><div className="metrics-grid"><MetricCard label="All-time participants" value={q.data.all_time_participants}/><MetricCard label="Weekly participants" value={q.data.weekly_participants}/><MetricCard label="XP today" value={q.data.xp_today}/><MetricCard label="XP week" value={q.data.xp_week}/></div>{json(q.data.top_earners)}</>}</div>}
export function Security(){const q=useQuery({queryKey:['security'],queryFn:()=>get('/admin/control/security')});return <div><h1>Security & Risk</h1><Loading query={q}/>{q.data&&<><MetricCard label="Banned users" value={q.data.banned_users}/><h2>Role changes</h2>{json(q.data.recent_role_changes)}<h2>Destructive actions</h2>{json(q.data.recent_destructive_actions)}<h2>Credit anomalies</h2><p>{q.data.credit_rule}</p>{json(q.data.suspicious_credit_usage)}</>}</div>}
export function ContentDetail(){const {id}=useParams();const navigate=useNavigate();const qc=useQueryClient();const q=useQuery({queryKey:['content-detail',id],queryFn:()=>get(`/admin/control/content/${id}`)});const flag=useMutation({mutationFn:reason=>client.post(`/admin/books/${id}/flag`,null,{params:{reason}}),onSuccess:()=>qc.invalidateQueries({queryKey:['content-detail',id]})});const remove=useMutation({mutationFn:reason=>client.delete(`/admin/books/${id}`,{params:{reason}}),onSuccess:()=>navigate('/content')});const ask=(kind)=>{const reason=window.prompt(`${kind === 'delete' ? 'Permanent deletion' : 'Moderation'} reason (required):`);if(!reason||reason.trim().length<3)return;if(kind==='delete'){if(window.confirm('Permanently delete this book and its related study content? This cannot be undone.'))remove.mutate(reason.trim())}else flag.mutate(reason.trim())};return <div><Link to="/content">← Content</Link><h1>Content Details</h1><Loading query={q}/>{q.data&&<><div className="detail-actions">{!q.data.flagged&&<button onClick={()=>ask('flag')}>Flag content</button>}<button className="btn-danger" onClick={()=>ask('delete')}>Permanently delete</button></div>{json(q.data)}</>}</div>}
export function CreditMonitoring(){const [page,setPage]=useState(1);const q=useQuery({queryKey:['credit-monitor',page],queryFn:()=>get('/admin/control/credits',{page,size:50})});const cols=[{key:'created_at',label:'Time',render:r=>when(r.created_at)},{key:'user_id',label:'User',render:r=><Link to={`/users/${r.user_id}`}>{r.user_id}</Link>},{key:'pool',label:'Pool'},{key:'amount',label:'Amount'},{key:'reason',label:'Reason'},{key:'expires_at',label:'Expires',render:r=>when(r.expires_at)}];return <div><h1>Usage & Credits</h1><Loading query={q}/>{q.data&&<><p>{q.data.authority}</p><div className="metrics-grid">{q.data.pools.map(x=><MetricCard key={x.pool} label={`${x.pool}: remaining / granted / used`} value={`${x.current_net} / ${x.granted} / ${x.consumed}`}/>)}</div><DataTable columns={cols} rows={q.data.items} page={page} total={q.data.total} size={50} onPageChange={setPage}/></>}</div>}
export function LearningActivity(){const q=useQuery({queryKey:['learning-monitor'],queryFn:()=>get('/admin/control/learning')});return <div><h1>Learning Activity</h1><Loading query={q}/>{q.data&&<><div className="metrics-grid">{Object.entries(q.data).filter(([,v])=>typeof v==='number').map(([k,v])=><MetricCard key={k} label={k.replaceAll('_',' ')} value={v}/>)}</div><p>{q.data.mastery_definition}</p></>}</div>}
