import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import client from '../api/client';
import { DailyBrief, Forecasts, IntelligenceAndRevenue, SystemHealth } from '../components/ExecutiveSections';
import DecisionPlatform from '../components/DecisionPlatform';

const money = (v) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v||0);
const value = (m) => m.value == null ? 'Unavailable' : m.format==='currency'?money(m.value):m.format==='percent'?`${m.value.toFixed(1)}%`:Math.round(m.value).toLocaleString();
const get = async (url,params) => (await client.get(url,{params})).data;
function Freshness({data}) { if(!data)return null; return <div className={`owner-fresh ${data.stale?'stale':''}`}>Updated {new Date(data.last_updated).toLocaleString()} · Stripe {data.stripe_sync_time?new Date(data.stripe_sync_time).toLocaleString():'No sync'} · AI {data.ai_sync_time?new Date(data.ai_sync_time).toLocaleString():'No sync'}{data.stale?' · Data is stale':''}</div> }
function Loading(){return <div className="owner-skeleton"><i/><i/><i/><i/></div>}
function ErrorBox({error}){return <div className="owner-error">Could not load this section. {error?.response?.data?.detail||'Try refreshing.'}</div>}

export default function OwnerDashboard(){
 const [page,setPage]=useState(1),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[segment,setSegment]=useState(''),[sort,setSort]=useState('contribution_margin'),[direction,setDirection]=useState('asc'),[selected,setSelected]=useState(null);
 const summary=useQuery({queryKey:['owner-summary'],queryFn:()=>get('/admin/owner-dashboard/summary')});
 const cash=useQuery({queryKey:['owner-cash'],queryFn:()=>get('/admin/owner-dashboard/cash-position')});
 const alerts=useQuery({queryKey:['owner-alerts'],queryFn:()=>get('/admin/owner-dashboard/alerts')});
 const units=useQuery({queryKey:['owner-units',page,search,status,segment,sort,direction],queryFn:()=>get('/admin/owner-dashboard/unit-economics',{page,page_size:20,search:search||undefined,status:status||undefined,segment:segment||undefined,sort,direction})});
 const detail=useQuery({queryKey:['owner-user',selected],queryFn:()=>get(`/admin/owner-dashboard/users/${selected}`),enabled:!!selected});
 const refresh=()=>{summary.refetch();cash.refetch();alerts.refetch();units.refetch()};
 const sortBy=(key)=>{if(sort===key)setDirection(x=>x==='asc'?'desc':'asc');else{setSort(key);setDirection('desc')}};
 const csv=()=>{const rows=units.data?.items||[];const headers=['User','Email','Plan','Interval','Revenue','AI Cost','Processing Cost','Storage Cost','Email Cost','Infrastructure Cost','Total Variable Cost','Margin','Margin %','Lifetime Value','Health Score','Documents','Last Active','Status','Flags'];const body=rows.map(r=>[r.user,r.email,r.plan,r.billing_interval,r.recognized_revenue,r.ai_cost,r.payment_processing_cost,r.storage_cost,r.email_cost,r.infrastructure_cost,r.total_variable_cost,r.contribution_margin,r.margin_pct,r.lifetime_value,r.customer_health_score,r.documents,r.last_active,r.status,r.flags.join('|')]);const esc=x=>`"${String(x??'').replaceAll('"','""')}"`;const blob=new Blob([[headers,...body].map(r=>r.map(esc).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mindflip-unit-economics.csv';a.click();URL.revokeObjectURL(a.href)};
 const shortcuts=[['Users','/users'],['Billing','/admin/financial-analytics'],['Subscriptions','/admin/financial-analytics'],['Invoices','/admin/financial-analytics'],['Payments','/admin/financial-analytics'],['Refunds','/admin/financial-analytics'],['AI Usage','/admin/ai-usage'],['AI Costs','/admin/ai-usage'],['Announcements','/admin/app-monitoring'],['Support Tickets','/feedback'],['Feature Flags','/admin/app-monitoring'],['System Health','/admin/app-monitoring'],['Logs','/admin/app-monitoring'],['Background Jobs','/admin/app-monitoring'],['Audit Logs','/admin/app-monitoring']];
 return <div className="owner-page">
  <header className="owner-header"><div><span className="owner-eyebrow">Executive command center</span><h1>Owner Dashboard</h1><p>Recurring revenue, unit economics, AI spend, and operational risk.</p></div><button onClick={refresh}>Refresh data</button></header>
  <DecisionPlatform />
  <DailyBrief />
  {summary.isLoading?<Loading/>:summary.isError?<ErrorBox error={summary.error}/>:<><Freshness data={summary.data.freshness}/><section className="owner-metrics">{summary.data.metrics.map(m=><article key={m.key} title={m.definition||m.tooltip}><div><span>{m.label}</span><b>ⓘ</b></div><em className={`metric-state ${m.status}`}>{m.status}</em><strong>{value(m)}</strong><small className={m.trend}>{m.trend==='up'?'↑':m.trend==='down'?'↓':m.trend==='unavailable'?'—':'→'} {m.reason||m.warning||(m.change_pct==null?'Historical comparison unavailable':`${Math.abs(m.change_pct)}% vs previous month`)}</small></article>)}</section></>}
  <div className="owner-grid">
   <section className="owner-card cash-card"><div className="section-title"><div><span className="owner-eyebrow">Liquidity</span><h2>Estimated Spendable Cash</h2></div></div>{cash.isLoading?<Loading/>:cash.isError?<ErrorBox error={cash.error}/>:<><div className="assumption">⚠ Uses reserve assumptions — this is not a bank balance.</div><div className="cash-total"><span>Estimated spendable · {cash.data.cash_runway_months} months known-cost runway</span><strong>{money(cash.data.estimated_spendable_cash)}</strong></div><div className="cash-stack">{[['deferred_revenue','Deferred','#8b5cf6'],['refund_dispute_reserve','Refund reserve','#f59e0b'],['tax_reserve','Tax reserve','#ef4444'],['minimum_cash_buffer','Buffer','#64748b'],['estimated_spendable_cash','Spendable','#10b981']].map(([k,l,c])=><i key={k} title={`${l}: ${money(cash.data[k])}`} style={{width:`${cash.data.cash_available?cash.data[k]/cash.data.cash_available*100:0}%`,background:c}}/>)}</div><div className="cash-lines">{[['Cash available','cash_available'],['Deferred revenue','deferred_revenue'],['Refund / dispute reserve','refund_dispute_reserve'],['Tax reserve','tax_reserve'],['Payroll reserve','payroll_reserve'],['Infrastructure reserve','infrastructure_reserve'],['Operating liabilities','operating_liabilities'],['Minimum cash buffer','minimum_cash_buffer']].map(([l,k])=><div key={k}><span>{l}</span><b>{money(cash.data[k])}</b></div>)}</div><details><summary>Calculation assumptions</summary>{cash.data.assumptions.map(x=><p key={x}>{x}</p>)}</details></>}
   </section>
   <section className="owner-card alert-card"><div className="section-title"><div><span className="owner-eyebrow">Risk queue</span><h2>Business Alerts</h2></div><b>{alerts.data?.items.length||0} open</b></div>{alerts.isLoading?<Loading/>:alerts.isError?<ErrorBox error={alerts.error}/>:alerts.data.items.length===0?<div className="owner-empty">✓ No canonical-data alerts need attention.</div>:alerts.data.items.map(a=><article className={`alert ${a.severity}`} key={a.id}><span>{a.severity}</span><div><b>{a.title}</b><p>{a.description}</p><small>Last detected {new Date(a.last_detected).toLocaleString()}</small></div><a href={a.action_url}>Review →</a></article>)}</section>
  </div>
  <Forecasts />
  <IntelligenceAndRevenue />
  <section className="owner-card units"><div className="section-title"><div><span className="owner-eyebrow">Customer profitability</span><h2>Unit Economics</h2></div><button onClick={csv} disabled={!units.data?.items.length}>Export CSV</button></div><div className="unit-tools"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search user, email, or plan…"/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option><option>active</option><option>trialing</option><option>past_due</option></select><select value={segment} onChange={e=>{setSegment(e.target.value);setPage(1)}}><option value="">All customer segments</option><option value="negative_margin">Negative margin</option><option value="inactive">Inactive customers</option><option value="high_ai">High AI spend</option><option value="high_revenue">High revenue</option><option value="high_profit">High profit</option><option value="enterprise">Enterprise users</option><option value="annual">Annual plans</option><option value="monthly">Monthly plans</option></select></div>{units.isLoading?<Loading/>:units.isError?<ErrorBox error={units.error}/>:units.data.items.length===0?<div className="owner-empty">No paying users match these filters.</div>:<><div className="owner-table-wrap"><table className="owner-table"><thead><tr>{[['user','User'],['plan','Plan'],['interval','Interval'],['recognized_revenue','Revenue'],['ai_cost','AI Cost'],['processing','Processing'],['variable','Variable Cost'],['contribution_margin','Margin'],['margin_pct','Margin %'],['ltv','LTV'],['health','Health'],['documents','Docs'],['last_active','Last Active'],['status','Status']].map(([k,l])=><th key={k}><button onClick={()=>['user','plan','recognized_revenue','ai_cost','contribution_margin','last_active'].includes(k)&&sortBy(k)}>{l}{sort===k?(direction==='asc'?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{units.data.items.map(r=><tr key={r.user_id} className={r.flags.join(' ')} onClick={()=>setSelected(r.user_id)}><td><b>{r.user}</b><small>{r.email}</small></td><td>{r.plan}</td><td>{r.billing_interval||'—'}</td><td>{money(r.recognized_revenue)}</td><td>{money(r.ai_cost)}</td><td>{money(r.payment_processing_cost)}</td><td>{money(r.total_variable_cost)}</td><td>{money(r.contribution_margin)}</td><td>{r.margin_pct.toFixed(1)}%</td><td>{money(r.lifetime_value)}</td><td><b>{r.customer_health_score}</b>/100</td><td>{r.documents}</td><td>{r.last_active?new Date(r.last_active).toLocaleDateString():'Never'}</td><td><span className="status-pill">{r.status}</span></td></tr>)}</tbody></table></div><div className="pagination"><span>{units.data.total} users · page {page} of {Math.max(1,Math.ceil(units.data.total/20))}</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={page*20>=units.data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></>}
  </section>
  <SystemHealth />
  <section><div className="section-title"><div><span className="owner-eyebrow">Navigate</span><h2>Management Shortcuts</h2></div></div><div className="shortcuts">{shortcuts.map(([l,u])=><a href={u} key={l}><span>{l}</span><b>↗</b></a>)}</div></section>
  {selected&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="owner-drawer" onMouseDown={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button>{detail.isLoading?<Loading/>:detail.isError?<ErrorBox error={detail.error}/>:detail.data&&<><span className="owner-eyebrow">Customer economics</span><h2>{detail.data.profile.name}</h2><p>{detail.data.profile.email} · {detail.data.profile.country||'Unknown location'}</p><div className="drawer-stats"><article><span>Recognized revenue</span><b>{money(detail.data.recognized_revenue)}</b></article><article><span>Refunds</span><b>{money(detail.data.refunds)}</b></article><article><span>Failed payments</span><b>{detail.data.failed_payments}</b></article><article><span>Total tokens</span><b>{Object.values(detail.data.token_usage).reduce((a,b)=>a+b,0).toLocaleString()}</b></article></div><h3>Subscription</h3><pre>{JSON.stringify(detail.data.subscription,null,2)}</pre><h3>AI cost by model</h3>{detail.data.ai_cost_by_model.map(x=><div className="drawer-line" key={x.label}><span>{x.label}</span><b>{money(x.cost)}</b></div>)}<h3>Recent AI activity</h3>{detail.data.recent_ai_activity.slice(0,10).map(x=><div className="activity" key={x.request_id}><b>{x.feature||'Unattributed'} · {x.model}</b><span>{x.status} · {x.input_tokens+x.output_tokens} tokens · {money(x.estimated_cost)}</span></div>)}</>}</aside></div>}
 </div>
}
