import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import client from '../api/client';

const get = async (url, params) => (await client.get(url, { params })).data;
const usd = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value || 0);

export default function DecisionPlatform() {
  const cache = useQueryClient();
  const [period, setPeriod] = useState('today');
  const [scenario, setScenario] = useState({ price_change: 0, ai_cost_reduction_pct: 0, conversion_change_pct: 0, churn_reduction_pct: 0 });
  const [goal, setGoal] = useState({ metric: 'mrr', label: 'MRR target', target: 5000 });
  const [watch, setWatch] = useState({ type: 'metric', id: 'mrr', label: 'MRR' });
  const decisions = useQuery({ queryKey: ['owner-decisions'], queryFn: () => get('/admin/owner-dashboard/decision-center') });
  const timeline = useQuery({ queryKey: ['owner-timeline', period], queryFn: () => get('/admin/owner-dashboard/timeline', { period }) });
  const preferences = useQuery({ queryKey: ['owner-preferences'], queryFn: () => get('/admin/owner-dashboard/preferences') });
  const simulation = useMutation({ mutationFn: body => client.post('/admin/owner-dashboard/simulate', body).then(x => x.data) });
  const save = useMutation({ mutationFn: body => client.put('/admin/owner-dashboard/preferences', body).then(x => x.data), onSuccess: data => cache.setQueryData(['owner-preferences'], data) });
  const addGoal = event => { event.preventDefault(); const current = preferences.data || { goals: [], watchlist: [] }; save.mutate({ ...current, goals: [...current.goals.filter(x => x.metric !== goal.metric), { ...goal, target: Number(goal.target) }] }); };
  const addWatch = event => { event.preventDefault(); const current = preferences.data || { goals: [], watchlist: [] }; if (!watch.label.trim()) return; save.mutate({ ...current, watchlist: [...current.watchlist.filter(x => !(x.type === watch.type && x.id === watch.id)), { ...watch, id: watch.id || watch.label.toLowerCase(), label: watch.label.trim() }] }); };
  const exportReport = async format => { const response = await client.get('/admin/owner-dashboard/reports/weekly', { params: { format }, responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = `mindflip-weekly-report.${format === 'markdown' ? 'md' : format}`; link.click(); URL.revokeObjectURL(url); };
  return <>
    <section className="decision-center"><div className="section-title"><div><span className="owner-eyebrow">Prioritized by business impact</span><h2>Decision Center</h2></div><span>{decisions.data?.items.length || 0} decisions</span></div>{decisions.isLoading ? <div className="exec-loading">Evaluating live business signals…</div> : decisions.data?.items.length ? <div className="decision-list">{decisions.data.items.map(item => <article className={item.priority} key={item.id}><header><span>{item.priority} priority</span><b>{item.title}</b></header><dl><div><dt>Why</dt><dd>{item.why}</dd></div><div><dt>Impact</dt><dd>{item.impact}</dd></div><div><dt>If ignored</dt><dd>{item.if_ignored}</dd></div></dl><footer><p><b>Recommended:</b> {item.recommended_action}</p><a href={item.action_url}>Open workflow →</a></footer></article>)}</div> : <div className="owner-empty">✓ {decisions.data?.empty_message}</div>}</section>
    <div className="decision-tools">
      <section className="owner-card"><div className="section-title"><div><span className="owner-eyebrow">Read-only planning</span><h2>Scenario Simulator</h2></div></div><div className="sim-inputs">{[['price_change','Pro price change ($)'],['ai_cost_reduction_pct','AI cost reduction (%)'],['conversion_change_pct','Conversion change (%)'],['churn_reduction_pct','Churn reduction (%)']].map(([key,label]) => <label key={key}>{label}<input type="number" value={scenario[key]} onChange={e => setScenario({ ...scenario, [key]: Number(e.target.value) })}/></label>)}</div><button className="primary-action" onClick={() => simulation.mutate(scenario)}>Run scenario</button>{simulation.data && <div className="scenario-results">{Object.entries(simulation.data.projected).map(([key,value]) => <span key={key}>{key.replaceAll('_',' ')}<b>{key.includes('pct') ? `${value}%` : key.includes('months') ? `${value} mo` : usd(value)}</b><small>{simulation.data.delta[key] >= 0 ? '+' : ''}{simulation.data.delta[key]}</small></span>)}</div>}</section>
      <section className="owner-card"><div className="section-title"><div><span className="owner-eyebrow">Owner targets</span><h2>Goals & Watchlist</h2></div></div><form className="goal-form" onSubmit={addGoal}><select value={goal.metric} onChange={e => setGoal({ ...goal, metric: e.target.value, label: `${e.target.options[e.target.selectedIndex].text} target` })}><option value="mrr">MRR</option><option value="ai_month">AI spend budget</option><option value="gross_margin">Gross margin</option><option value="trial_conversion">Conversion</option><option value="monthly_churn">Churn</option><option value="estimated_runway">Runway</option></select><input type="number" value={goal.target} onChange={e => setGoal({ ...goal, target: e.target.value })}/><button>Add target</button></form><div className="goal-list">{preferences.data?.goals.map(x => <article key={x.metric}><span>{x.label}</span><b>{x.target.toLocaleString()}</b><button onClick={() => save.mutate({ ...preferences.data, goals: preferences.data.goals.filter(g => g.metric !== x.metric) })}>×</button></article>)}{!preferences.data?.goals.length && <p>No executive targets defined yet.</p>}</div><form className="goal-form watch-form" onSubmit={addWatch}><select value={watch.type} onChange={e => setWatch({ ...watch, type: e.target.value })}>{['customer','plan','country','model','segment','feature_flag','metric'].map(x => <option key={x}>{x}</option>)}</select><input value={watch.label} onChange={e => setWatch({ ...watch, id: e.target.value.toLowerCase(), label: e.target.value })} placeholder="Name or identifier"/><button>Pin</button></form><div className="watch-chips">{preferences.data?.watchlist.map(x => <button key={`${x.type}${x.id}`} onClick={() => save.mutate({ ...preferences.data, watchlist: preferences.data.watchlist.filter(w => !(w.type === x.type && w.id === x.id)) })}>{x.type}: {x.label} ×</button>)}</div><div className="report-actions"><b>Weekly report</b>{['pdf','markdown','csv'].map(x => <button key={x} onClick={() => exportReport(x)}>Download {x.toUpperCase()}</button>)}</div></section>
    </div>
    <section className="owner-card change-timeline"><div className="section-title"><div><span className="owner-eyebrow">Change intelligence</span><h2>What Changed?</h2></div><select value={period} onChange={e => setPeriod(e.target.value)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7d">7 days</option><option value="30d">30 days</option></select></div><div>{timeline.data?.items.length ? timeline.data.items.map((x,index) => <article key={`${x.type}${x.occurred_at}${index}`}><i/><time>{new Date(x.occurred_at).toLocaleString()}</time><div><b>{x.title}</b><p>{x.description}</p></div></article>) : <div className="owner-empty">No material canonical-data changes in this period.</div>}</div></section>
  </>;
}
