import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHero, Reveal } from '@/components/MarketingUI';
import { CTABanner } from '@/components/CTABanner';

export const metadata: Metadata = { title: 'How It Works', description: 'See how Mindflip turns your course material into an adaptive study system.', alternates: { canonical: 'https://mindflip.io/how-it-works' } };

const stages = [
  { number: '01', eyebrow: 'Bring your material', title: 'Start with what you actually need to learn.', body: 'Upload a textbook chapter, lecture notes, or a PDF. Mindflip keeps the learning experience grounded in your source instead of a generic question bank.', details: ['PDF and text-based materials', 'Private, user-scoped content', 'Organized by book and chapter'], visual: <div className="relative h-full min-h-72 overflow-hidden rounded-[2rem] bg-[#11142c] p-7 text-white"><div className="absolute -right-16 -top-16 h-56 w-56 rounded-full bg-indigo-500/30 blur-3xl"/><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><span className="rounded-md bg-rose-500 px-2 py-1 text-[10px] font-bold">PDF</span><p className="mt-5 font-bold">Cognitive Psychology: Chapter 4</p><div className="mt-4 space-y-2 opacity-40"><div className="h-2 rounded bg-white"/><div className="h-2 w-4/5 rounded bg-white"/><div className="h-2 w-11/12 rounded bg-white"/></div></div><div className="absolute bottom-6 left-12 right-3 rounded-2xl bg-white p-4 text-gray-900 shadow-2xl"><p className="text-xs font-bold text-indigo-600">Upload complete</p><p className="mt-1 text-sm">Ready to build your study set</p></div></div> },
  { number: '02', eyebrow: 'Mindflip builds', title: 'AI turns information into active recall.', body: 'The study engine extracts concepts and relationships, then creates flashcards, quiz questions, summaries, and realistic scenarios in one connected workflow.', details: ['Concept-aware flashcards', 'Questions at multiple cognitive levels', 'Summaries and applied scenarios'], visual: <div className="grid h-full min-h-72 gap-3 rounded-[2rem] bg-indigo-50 p-6 sm:grid-cols-2"><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-indigo-600">Concept card</p><p className="mt-6 font-bold">What is retrieval practice?</p><div className="mt-8 rounded-xl bg-indigo-50 p-3 text-xs text-indigo-800">Actively recalling information to strengthen memory.</div></div><div className="space-y-3"><div className="rounded-2xl bg-indigo-600 p-5 text-white"><p className="text-xs font-bold text-indigo-200">Quiz ready</p><p className="mt-2 text-3xl font-black">12</p><p className="text-xs text-indigo-200">adaptive questions</p></div><div className="rounded-2xl bg-emerald-100 p-5"><p className="text-xs font-bold text-emerald-800">Scenario generated</p><p className="mt-2 text-sm font-semibold">Apply the idea in a real context</p></div></div></div> },
  { number: '03', eyebrow: 'Practice and adapt', title: 'Every answer improves what comes next.', body: 'Study with cards, quizzes, and games. Your review queue responds to performance, bringing difficult material back sooner and confident material back later.', details: ['Adaptive spaced repetition', 'Multiple practice modes', 'Clear progress and daily review'], visual: <div className="h-full min-h-72 rounded-[2rem] bg-[#fff7ea] p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-amber-700">Today’s review</p><p className="mt-1 text-3xl font-black">18 cards</p></div><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white text-2xl shadow-sm">◷</span></div><div className="mt-8 space-y-3">{[['Memory consolidation','Now','bg-rose-400'],['Interleaving','2 days','bg-amber-400'],['Active recall','6 days','bg-emerald-400']].map(([name,time,color])=><div key={name} className="flex items-center gap-3 rounded-xl bg-white p-3"><span className={`h-2.5 w-2.5 rounded-full ${color}`}/><span className="flex-1 text-sm font-bold">{name}</span><span className="text-xs text-gray-500">{time}</span></div>)}</div></div> },
  { number: '04', eyebrow: 'Build momentum', title: 'See progress without obsessing over it.', body: 'Mindflip turns consistent effort into visible progress through streaks, goals, achievements, and collaborative study. Every feature is designed to support learning without distracting from it.', details: ['Meaningful learning analytics', 'Study groups and challenges', 'Goals, streaks, and achievements'], visual: <div className="h-full min-h-72 rounded-[2rem] bg-[#eafaf6] p-7"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">This week</p><div className="mt-6 flex items-end justify-between gap-2">{[38,55,30,78,65,92,74].map((height,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-lg bg-emerald-400" style={{height}}/><span className="text-[9px] font-bold text-emerald-800">{'MTWTFSS'[i]}</span></div>)}</div><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white p-4"><p className="text-2xl font-black">84%</p><p className="text-xs text-gray-500">retention score</p></div><div className="rounded-xl bg-white p-4"><p className="text-2xl font-black">7 🔥</p><p className="text-xs text-gray-500">day streak</p></div></div></div> },
];

export default function HowItWorksPage() {
  return <><PageHero eyebrow="The Mindflip method" title="From source material to" accent="lasting memory." description="A focused four-stage learning loop removes setup work, makes practice active, and keeps review aligned with your memory."/>
    <section className="section-shell py-24 sm:py-32"><div className="space-y-24 sm:space-y-32">{stages.map((stage,index)=><Reveal key={stage.number}><article className={`grid gap-10 lg:grid-cols-2 lg:items-center ${index%2 ? 'lg:[&>*:first-child]:order-2' : ''}`}><div><p className="text-sm font-black text-indigo-600">{stage.number} / 04</p><p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-gray-400">{stage.eyebrow}</p><h2 className="mt-3 text-4xl font-black tracking-[-0.04em] sm:text-5xl">{stage.title}</h2><p className="mt-5 max-w-xl text-lg leading-8 text-gray-600">{stage.body}</p><ul className="mt-7 space-y-3">{stage.details.map(item=><li key={item} className="flex items-center gap-3 text-sm font-semibold text-gray-700"><span className="grid h-5 w-5 place-items-center rounded-full bg-emerald-100 text-[10px] text-emerald-700">✓</span>{item}</li>)}</ul></div><div>{stage.visual}</div></article></Reveal>)}</div></section>
    <section className="border-y border-gray-200 bg-gray-50 py-20"><div className="section-shell flex flex-col items-center justify-between gap-8 text-center md:flex-row md:text-left"><div><p className="eyebrow">Want the full tour?</p><h2 className="mt-4 text-3xl font-black">Explore everything Mindflip can do.</h2></div><Link href="/features" className="button-primary">See all features →</Link></div></section><CTABanner/></>;
}
