import type { Metadata } from 'next';
import { PageHero, Reveal } from '@/components/MarketingUI';
import { CTABanner } from '@/components/CTABanner';

export const metadata: Metadata = { title: 'Features', description: 'Explore Bilkeys AI study tools, active recall, spaced repetition, games, groups, and learning analytics.', alternates: { canonical: 'https://bilkeys.io/features' } };

const groups = [
  { label: 'Create', title: 'From content to curriculum in moments', description: 'Spend your energy learning instead of formatting cards.', color: 'bg-indigo-50', items: [['AI flashcard generation','Extract the concepts that matter from your own source material.'],['Smart summaries','Get a structured overview before you dive into details.'],['Applied scenarios','Move beyond definitions and practice using what you know.'],['Content organization','Keep books, chapters, sets, and folders connected.']] },
  { label: 'Practice', title: 'Active learning in more than one mode', description: 'Switch formats to keep recall effortful and useful.', color: 'bg-amber-50', items: [['Adaptive quizzes','Test understanding with questions generated from your material.'],['Eight study games','Turn repetition into focused, varied practice.'],['Daily Review','Open the app and know exactly what deserves attention.'],['Spaced repetition','Review difficult ideas sooner and mastered ideas later.']] },
  { label: 'Connect', title: 'Motivation without the distraction', description: 'Social and progress features designed around the work.', color: 'bg-emerald-50', items: [['Study groups','Build shared momentum around common goals.'],['Quiz challenges','Practice with friends when competition helps.'],['Achievements and streaks','Recognize consistent learning behavior.'],['Learning analytics','See activity, retention, and progress over time.']] },
];

export default function FeaturesPage(){return <><PageHero eyebrow="The complete toolkit" title="Everything works together to make" accent="learning feel lighter." description="Creation, practice, review, and motivation share one system, so each session starts with clarity and ends with progress."/>
  <section className="section-shell py-24 sm:py-32"><div className="space-y-20">{groups.map((group,index)=><Reveal key={group.label}><div className={`rounded-[2.5rem] ${group.color} p-7 sm:p-10 lg:p-14`}><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><span className="text-xs font-black uppercase tracking-[0.2em] text-indigo-600">0{index+1}: {group.label}</span><h2 className="mt-5 text-3xl font-black tracking-[-0.04em] sm:text-5xl">{group.title}</h2><p className="mt-4 text-lg leading-8 text-gray-600">{group.description}</p></div><div className="grid gap-4 sm:grid-cols-2">{group.items.map(([title,body],i)=><article key={title} className="rounded-2xl border border-white/80 bg-white/80 p-6 shadow-sm backdrop-blur transition duration-300 hover:-translate-y-1 hover:shadow-lg"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-xs font-black text-white">{i+1}</span><h3 className="mt-6 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-600">{body}</p></article>)}</div></div></div></Reveal>)}</div></section>
  <section className="bg-[#11142c] py-24 text-white"><div className="section-shell text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-300">Built with restraint</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-black tracking-[-0.04em] sm:text-5xl">Powerful when you need it. Quiet when you don’t.</h2><div className="mx-auto mt-12 grid max-w-4xl gap-4 sm:grid-cols-3">{[['Private','Your learning content stays scoped to you.'],['Adaptive','The system responds to your performance.'],['Accessible','Responsive, keyboard-friendly experiences.']].map(([title,body])=><div key={title} className="rounded-2xl border border-white/10 bg-white/5 p-6"><p className="font-black">{title}</p><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></div>)}</div></div></section><CTABanner/></>}
