"""Country list and continent lookup for onboarding and analytics."""

from __future__ import annotations

# Static list used by clients; keep in sync with src/lib/countries.js
COUNTRIES: list[str] = sorted(
    [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Argentina",
        "Australia",
        "Austria",
        "Bangladesh",
        "Belgium",
        "Brazil",
        "Canada",
        "Chile",
        "China",
        "Colombia",
        "Czech Republic",
        "Denmark",
        "Egypt",
        "Ethiopia",
        "Finland",
        "France",
        "Germany",
        "Ghana",
        "Greece",
        "Hong Kong",
        "Hungary",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Japan",
        "Jordan",
        "Kenya",
        "Malaysia",
        "Mexico",
        "Morocco",
        "Netherlands",
        "New Zealand",
        "Nigeria",
        "Norway",
        "Pakistan",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "Saudi Arabia",
        "Sierra Leone",
        "Singapore",
        "South Africa",
        "South Korea",
        "Spain",
        "Sweden",
        "Switzerland",
        "Taiwan",
        "Thailand",
        "Turkey",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Vietnam",
        "Other",
    ],
    key=str.casefold,
)

COUNTRY_CONTINENT: dict[str, str] = {
    "Afghanistan": "Asia",
    "Albania": "Europe",
    "Algeria": "Africa",
    "Argentina": "South America",
    "Australia": "Oceania",
    "Austria": "Europe",
    "Bangladesh": "Asia",
    "Belgium": "Europe",
    "Brazil": "South America",
    "Canada": "North America",
    "Chile": "South America",
    "China": "Asia",
    "Colombia": "South America",
    "Czech Republic": "Europe",
    "Denmark": "Europe",
    "Egypt": "Africa",
    "Ethiopia": "Africa",
    "Finland": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Greece": "Europe",
    "Hong Kong": "Asia",
    "Hungary": "Europe",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Ireland": "Europe",
    "Israel": "Asia",
    "Italy": "Europe",
    "Japan": "Asia",
    "Jordan": "Asia",
    "Kenya": "Africa",
    "Malaysia": "Asia",
    "Mexico": "North America",
    "Morocco": "Africa",
    "Netherlands": "Europe",
    "New Zealand": "Oceania",
    "Nigeria": "Africa",
    "Norway": "Europe",
    "Pakistan": "Asia",
    "Peru": "South America",
    "Philippines": "Asia",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Romania": "Europe",
    "Russia": "Europe",
    "Saudi Arabia": "Asia",
    "Sierra Leone": "Africa",
    "Singapore": "Asia",
    "South Africa": "Africa",
    "South Korea": "Asia",
    "Spain": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Taiwan": "Asia",
    "Thailand": "Asia",
    "Turkey": "Asia",
    "Ukraine": "Europe",
    "United Arab Emirates": "Asia",
    "United Kingdom": "Europe",
    "United States": "North America",
    "Vietnam": "Asia",
}


def continent_for_country(country: str, *, custom_country: str | None = None) -> str | None:
    """Resolve continent from a selected country or custom country name."""
    if country.strip().lower() == "other":
        lookup = (custom_country or "").strip()
        if not lookup:
            return None
        return continent_for_country(lookup)

    key = country.strip()
    if key in COUNTRY_CONTINENT:
        return COUNTRY_CONTINENT[key]

    lowered = key.casefold()
    for name, continent in COUNTRY_CONTINENT.items():
        if name.casefold() == lowered:
            return continent
    return None
