[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_unused_ignores = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-tasks.ai_tasks]
disable_error_code = union-attr

[mypy-routers.ai]
disable_error_code = union-attr

[mypy-tests.test_books]
disable_error_code = misc

[mypy-main]
disable_error_code = misc
