/**
 * MindFlip Mobile Design Tokens
 * Centralized semantic design tokens for the MindFlip mobile application.
 *
 * Visual identity: "Focused Depth" — a calm neutral canvas with a scarce,
 * confident brand gradient reserved for hero surfaces, primary CTAs, the
 * active learning surface, and celebrations. See mobile/docs/MFUX_VISUAL_AUDIT.md.
 */

export const TOKENS = {
  colors: {
    light: {
      background: "#F6F5FC",
      surface: "#FCFCFE",
      surfaceElevated: "#FFFFFF",
      surfaceMuted: "#EDEBF7",
      surfaceBrand: "#E9E5FF",
      textPrimary: "#16142B",
      textSecondary: "#4A4766",
      textMuted: "#75718F",
      border: "#E6E3F2",
      borderStrong: "#CFCBE4",
      primary: "#4f46e5",
      primaryMuted: "#818cf8",
      primaryPressed: "#4338ca",
      primarySoft: "#E9E5FF",
      accentViolet: "#7C3AED",
      onPrimary: "#ffffff",
      onDanger: "#ffffff",
      onBrand: "#FFFFFF",
      success: "#047857",
      successSurface: "#D9F2E6",
      warning: "#b45309",
      warningSurface: "#FDF0D5",
      danger: "#B91C1C",
      dangerSurface: "#FCE4E4",
      info: "#0369A1",
      infoSurface: "#DDEEFA",
      xp: "#B45309",
      xpSurface: "#FDF0D5",
      streak: "#EA580C",
      streakSurface: "#FFE9DC",
      overlay: "rgba(22, 20, 43, 0.45)",
      skeleton: "#E4E1F5",
      cardFront: "#FFFFFF",
      cardBack: "#F1EEFF",
      orbWarm: "rgba(236, 72, 153, 0.22)",
      orbCool: "rgba(37, 99, 235, 0.20)",
    },
    dark: {
      background: "#0B0A15",
      surface: "#14131F",
      surfaceElevated: "#1D1B2C",
      surfaceMuted: "#191825",
      surfaceBrand: "#241E4B",
      textPrimary: "#F3F2FA",
      textSecondary: "#C4C1D8",
      textMuted: "#918DAE",
      border: "#2A2839",
      borderStrong: "#3B3852",
      primary: "#A78BFA",
      primaryMuted: "#C4B5FD",
      primaryPressed: "#8B5CF6",
      primarySoft: "#2A2350",
      accentViolet: "#A78BFA",
      onPrimary: "#120F26",
      onDanger: "#120F26",
      onBrand: "#FFFFFF",
      success: "#34d399",
      successSurface: "#123528",
      warning: "#fbbf24",
      warningSurface: "#3A2C0E",
      danger: "#f87171",
      dangerSurface: "#3A1414",
      info: "#38bdf8",
      infoSurface: "#0E2C3A",
      xp: "#fbbf24",
      xpSurface: "#3A2C0E",
      streak: "#fb923c",
      streakSurface: "#3A2410",
      overlay: "rgba(5, 4, 12, 0.72)",
      skeleton: "#221F33",
      cardFront: "#1D1B2C",
      cardBack: "#221F3D",
      orbWarm: "rgba(236, 72, 153, 0.16)",
      orbCool: "rgba(99, 102, 241, 0.20)",
    },
  },
  gradients: {
    light: {
      brand: ["#4F46E5", "#7C3AED"] as [string, string],
    },
    dark: {
      brand: ["#4C3AE0", "#7C3AED"] as [string, string],
    },
  },
  typography: {
    heroDisplay: {
      fontSize: 34,
      lineHeight: 40,
      fontWeight: "800" as const,
      letterSpacing: -0.6,
    },
    display: {
      fontSize: 30,
      lineHeight: 36,
      fontWeight: "800" as const,
      letterSpacing: -0.5,
    },
    screenTitle: {
      fontSize: 26,
      lineHeight: 32,
      fontWeight: "800" as const,
      letterSpacing: -0.4,
    },
    sectionTitle: {
      fontSize: 19,
      lineHeight: 24,
      fontWeight: "700" as const,
      letterSpacing: -0.2,
    },
    cardTitle: {
      fontSize: 16,
      lineHeight: 22,
      fontWeight: "700" as const,
    },
    cardBody: {
      fontSize: 21,
      lineHeight: 30,
      fontWeight: "500" as const,
    },
    body: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "400" as const,
    },
    bodyEmphasis: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "600" as const,
    },
    secondaryBody: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: "400" as const,
    },
    label: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "600" as const,
    },
    caption: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "500" as const,
    },
    eyebrow: {
      fontSize: 11,
      lineHeight: 14,
      fontWeight: "800" as const,
      letterSpacing: 1.4,
    },
    buttonLabel: {
      fontSize: 15,
      lineHeight: 20,
      fontWeight: "700" as const,
    },
    metric: {
      fontSize: 32,
      lineHeight: 36,
      fontWeight: "800" as const,
      letterSpacing: -0.5,
    },
    metricLabel: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "600" as const,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 40,
  },
  radii: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 9999,
    circular: 9999,
  },
  elevation: {
    flat: {
      shadowColor: "transparent",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    raised: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
    floating: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.14,
      shadowRadius: 12,
      elevation: 8,
    },
    sheet: {
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.18,
      shadowRadius: 16,
      elevation: 12,
    },
  },
  motion: {
    duration: {
      instant: 0,
      micro: 120,
      fast: 150,
      standard: 220,
      navigation: 260,
      deliberate: 400,
      celebration: 480,
    },
    spring: {
      tight: { damping: 20, stiffness: 200 },
      standard: { damping: 15, stiffness: 120 },
      gentle: { damping: 12, stiffness: 80 },
    },
  },
  layout: {
    minTouchTarget: 44,
  },
} as const;

export type ThemeMode = "light" | "dark";
export type ThemeColorTokens = typeof TOKENS.colors.light;
